version: '3'

networks:
  lumen:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver-login
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lumen

  mysql:
    image: mysql:5.7.29
    container_name: mysql-login
    restart: unless-stopped
    tty: true
    ports:
      - "4308:3306"
    environment:
      MYSQL_DATABASE: login
      MYSQL_USER: login
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login
    volumes:
      - ./src:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - lumen